import { Fragment } from "react";
import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <Fragment>
      <Head>
        <title>Spotify Network</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </Fragment>
  );
};

export default Layout;
